[package]
name = "excetera"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"
publish = false

[lib]
crate-type = ["staticlib"]
name = "excetera"

[dependencies]
extendr-api = "*"
tera = { version = "1.20", default-features = false }

[profile.release]
lto = true
codegen-units = 1