# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_excetera_wrappers", use_symbols = TRUE, package_name = "excetera")

#' @usage NULL
#' @useDynLib excetera, .registration = TRUE
NULL

render_template <- function(template, outfile, parameters) .Call(wrap__render_template, template, outfile, parameters)


# nolint end
